replicaCount: 2

image:
  repository: registry-1.docker.io/lpintofsgrp/frontend
  tag: "{{ tag }}"

service:
  type: ClusterIP
  port: 80          # Puerto expuesto al cluster (externo)
  targetPort: 8080  # Puerto interno del contenedor (Dockerfile)

route:
  enabled: true
  host: ""          # Deja vacío para que OpenShift genere automáticamente el hostname
