  replicaCount: 2
  image:
    repository: registry-1.docker.io/lpintofsgrp/frontend
    tag: "{{ tag }}"
  service:
    port: 80          # Puerto que expone el Service dentro del cluster y recibe la Route
    targetPort: 8080  # Puerto del contenedor
  route:
    enabled: true
    host: ""
  env:
    REACT_APP_API_URL: "https://backend-api-lpintofsgrp-dev.apps.rm1.0a51.p1.openshiftapps.com:8080"
