apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-route
  labels:
    app: frontend
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: {{ .Values.service.targetPort }}
  tls:
    termination: edge
